### ISSUE TITLE
Using nameof_member on structures with non-constexpr destructor fails to compile on MSVC

### ISSUE THREAD

**Issue by kamchatka-volcano** [Neargye/nameof#49]
Hi, I finally got around to updating nameof in my project to test the fix of #46 by @schaumb.
Unfortunately, it doesn't work when `TestStruct` has a member with a non-constexpr user-provided constructor. Is it possible to fix it?
I looked into the source, but I don't understand the union trick used in the `member_name_v` implementation for MSVC, so I can't tell if it can be fixed.

As previously, the following code doesn't compile on MSVC (2022) using the latest master of `nameof`, but works fine with clang and gcc
```
struct Foo{
    ~Foo(){};
};

struct TestStruct{
    std::string teststringfield = std::string{nameof::nameof_member<&TestStruct::teststringfield>()};
    Foo foo;
};
```

**Comment by schaumb** [comment]
Hi @kamchatka-volcano !
The current solution works only if the TestStruct **destructor** is constexpr, which is default for trivially_constructible classes, and if all member destructor is constexpr.

So If Foo's **destructor** is constexpr, then it will work. 


I Investigate any other solution for not constexpr destructor, but I think this is a MSVC compiler or C++std bug. It [must not to call](https://stackoverflow.com/a/40107282) members user-defined destructor in union, but constexpr-ness property is inherited somewhy, based on the [compiler error](https://godbolt.org/z/fWGaedGE8) 



[TODO doc!](https://github.com/Neargye/nameof/issues/47)

*note:*
*the union trick is simply: We create a constexpr static variable, which is an union with a trivial active type (char) and the class (T) of the owrner of member. We cannot use the not active member (T), but we can query the member pointer of the constexpr union variable. This "constexpr relative" memory information is passed through a \_\_FUNCSIGN__, and it will contains the name. So we won't create the TestStruct, and shoudn't be call the destructor either.*
*sidenote: this hack needed because \_\_FUNCSIGN__ is not contains the member pointer name default, only the offset*

**Comment by kamchatka-volcano** [comment]
I see, that's what I was afraid of) In my project `TestStruct` is user-provided and the requirement of constexpr dtr is a pretty heavy restriction.
Anyway, thanks a lot for the detailed explanation, now it's much more clear what's going on there. I'll try to think of some workaround as well.
